### ISSUE TITLE
Monitor IP and User Agents during change requests

### ISSUE THREAD

**Issue by shawnonthenet** [doomspork/companies#12]
Adding IP and UA logging to pending changes will allow admins to more quickly spot bots and regular bad actors and allow for automatic blocking in the future.  These details should also be shown on the change approval screen to allow admins to see them while accepting and rejecting changes.

To complete this the follow sub tasks will need to be completed

- [ ] Add ip_address and user_agent columns to pending changes
- [ ] Update create change function to fill the new columns(zero out the last octet or two from the ip to avoid storing PII and as bots often use multiple IPs in the same data centre)
- [ ] Update the admin change panel to display the new details

**Comment by shawnonthenet** [comment]
@doomspork If you can give me a shout when your auth PR is merged I'd be happy to knock this one out.

**Comment by doomspork** [comment]
Heck _yeah_ @shawnonthenet! I will try to wrap that PR up over the next day or so.

**Comment by shawnonthenet** [comment]
Switched this to showing the username instead.  Fixed in #24
