### ISSUE TITLE
Creating company while logged out generates error

### ISSUE THREAD

**Issue by shawnonthenet** [doomspork/companies#17]
Working through #12 and running into an issue.  Not sure if this is just because I haven't setup the github integration yet but as a logged out user when trying to create a new company I am getting the following error:

no function clause matching in Companies.PendingChanges.insert_change/4

The last param for insert_change is nil when logged out when the only function def requires a map.

To recreate log out and try to add a company.

**Comment by doomspork** [comment]
@shawnonthenet that is a bug. For _now_, we're going to require someone log in to create an account. If you need help setting up GH let me know, happy to walk you through it.

If you'd rather not have to worry about that stuff you could run the seed and hard code in the system's user: https://github.com/doomspork/companies/blob/master/lib/companies_web/helpers/user_helpers.ex#L11

**Comment by shawnonthenet** [comment]
@doomspork Sounds good.  I'm just setting up the oauth stuff now but thanks for the offer.
